import './globals.css';
import { Poppins } from '@next/font/google';
import Sidebar from '@/app/Sidebar/Sidebar';

const font = Poppins({
	weight: ['400', '500', '600', '700', '800'],
	subsets: ['latin'],
});

export const metadata = {
	title: 'Vito Service',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body
				className={font.className}
				style={{ display: 'flex', background: '#161616', color: '#fff' }}
				data-gr-c-s-loaded
			>
				<Sidebar />
				<main>{children}</main>
			</body>
		</html>
	);
}
